### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DawoodMehmood** [DawoodMehmood/spin-wheel#1]
- [ ] text box to enter values separated by newline
- [ ] spin wheel rotates by clicking in the center of the wheel
- [ ] wheel stops and show a modal with winner name and button to remove this name from list
- [ ] wheel stops and confetti pops all over the screen behind the winner modal
- [ ] add sound effects on wheel rotation and stopping and announcing winner
- [ ] give hand pointer to rotate the wheel with as variable speed
